DROP SCHEMA IF EXISTS moodreboot;
CREATE SCHEMA moodreboot;
USE moodreboot;

CREATE TABLE APP_FILE (
    FILE_ID INT NOT NULL,
    USER_ID INT NULL,
    MIME_TYPE NVARCHAR(100) NOT NULL,
    NAME LONGTEXT NOT NULL,
    PRIMARY KEY (FILE_ID)
) ENGINE=InnoDB;

CREATE TABLE APP_USER (
    USER_ID INT NOT NULL,
    EMAIL NVARCHAR(255) NOT NULL,
    PASSWORD LONGBLOB NOT NULL,
    USERNAME NVARCHAR(20) NOT NULL,
    FIRST_NAME NVARCHAR(20) NOT NULL,
    LAST_NAME NVARCHAR(30) NOT NULL,
    SIGN_DATE DATETIME NOT NULL,
    IMAGE LONGTEXT,
    ROLE NVARCHAR(10) NOT NULL,
    LAST_SEEN DATETIME,
    SALT LONGTEXT NOT NULL,
    PASS_TEST LONGTEXT,
    APPROVED BIT NOT NULL,
    PRIMARY KEY (USER_ID)
) ENGINE=InnoDB;

CREATE TABLE CENTER (
    CENTER_ID INT NOT NULL,
    EMAIL NVARCHAR(255) NOT NULL,
    NAME NVARCHAR(50) NOT NULL,
    ADDRESS NVARCHAR(150) NOT NULL,
    IMAGE LONGTEXT NOT NULL,
    TELEPHONE NVARCHAR(15) NOT NULL,
    DIRECTOR INT NOT NULL,
    APPROVED BIT NOT NULL,
    PRIMARY KEY (CENTER_ID)
) ENGINE=InnoDB;

CREATE TABLE CHAT_GROUP (
    GROUP_ID INT NOT NULL,
    IMAGE LONGTEXT,
    NAME NVARCHAR(40) NOT NULL,
    PRIMARY KEY (GROUP_ID)
) ENGINE=InnoDB;

CREATE TABLE CHAT_MESSAGE (
    MESSAGE_ID INT NOT NULL,
    GROUP_ID INT NOT NULL,
    TEXT NVARCHAR(350),
    USER_ID INT,
    DATE_POSTED DATETIME NOT NULL,
    FILE_ID INT,
    USERNAME NVARCHAR(30) NOT NULL,
    PRIMARY KEY (MESSAGE_ID)
) ENGINE=InnoDB;

CREATE TABLE CONTENT (
    CONTENT_ID INT NOT NULL,
    TEXT LONGTEXT,
    GROUP_CONTENT_ID INT NOT NULL,
    FILE_ID INT,
    PRIMARY KEY (CONTENT_ID)
) ENGINE=InnoDB;

CREATE TABLE CONTENT_COURSE (
    GROUP_CONTENT_ID INT NOT NULL,
    NAME NVARCHAR(50) NOT NULL,
    IS_VISIBLE BIT NOT NULL,
    COURSE_ID INT NOT NULL,
    PRIMARY KEY (GROUP_CONTENT_ID)
) ENGINE=InnoDB;

CREATE TABLE COURSE (
    COURSE_ID INT NOT NULL,
    DATE_PUBLISHED DATETIME NOT NULL,
    DATE_MODIFIED DATETIME,
    DESCRIPTION NVARCHAR(350),
    IMAGE LONGTEXT,
    NAME NVARCHAR(50) NOT NULL,
    CENTER_ID INT NOT NULL,
    IS_VISIBLE BIT NOT NULL,
    GROUP_ID INT,
    PASSWORD NVARCHAR(12),
    PRIMARY KEY (COURSE_ID)
) ENGINE=InnoDB;

CREATE TABLE USER_ACTION (
    ID INT NOT NULL,
    USER_ID INT NOT NULL,
    TOKEN LONGTEXT NOT NULL,
    REQUEST_DATE DATETIME NOT NULL,
    PRIMARY KEY (ID)
) ENGINE=InnoDB;

CREATE TABLE USER_CENTER (
    ID INT NOT NULL,
    USER_ID INT NOT NULL,
    CENTER_ID INT NOT NULL,
    IS_EDITOR BIT NOT NULL,
    PRIMARY KEY (ID)
) ENGINE=InnoDB;

CREATE TABLE USER_COURSE (
    ID INT NOT NULL,
    USER_ID INT NOT NULL,
    COURSE_ID INT NOT NULL,
    IS_EDITOR BIT NOT NULL,
    PRIMARY KEY (ID)
) ENGINE=InnoDB;

CREATE TABLE `USER_GROUP` (
  `ID` int NOT NULL,
  `USER_ID` int NOT NULL,
  `GROUP_ID` int DEFAULT NULL,
  `JOIN_DATE` datetime NOT NULL,
  `LAST_SEEN` datetime NOT NULL,
  `IS_ADMIN` bit NOT NULL
);

/******************** ALTER TABLE ********************/

ALTER TABLE APP_USER ADD CONSTRAINT UQ_USER_161CF72423A73214 UNIQUE 
(
    EMAIL
);

ALTER TABLE APP_USER ADD CONSTRAINT UQ_USER_B15BE12E9D472A34 UNIQUE 
(
    USERNAME
);

ALTER TABLE APP_USER ADD CONSTRAINT UQ__USER__B15BE12ED1B98C1E UNIQUE (USERNAME);

ALTER TABLE APP_FILE ADD CONSTRAINT FK_APP_FILE_APP_USER FOREIGN KEY (USER_ID)
REFERENCES APP_USER (USER_ID)
ON DELETE CASCADE;

ALTER TABLE CHAT_MESSAGE ADD CONSTRAINT FK_CHAT_MESSAGE_APP_FILE FOREIGN KEY (FILE_ID)
REFERENCES APP_FILE (FILE_ID);

ALTER TABLE CHAT_MESSAGE ADD CONSTRAINT FK_CHAT_MESSAGE_APP_USER FOREIGN KEY (USER_ID)
REFERENCES APP_USER (USER_ID)
ON DELETE SET NULL;

ALTER TABLE CHAT_MESSAGE ADD CONSTRAINT FK_MESSAGE_GROUP FOREIGN KEY (GROUP_ID)
REFERENCES CHAT_GROUP (GROUP_ID)
ON DELETE CASCADE;

ALTER TABLE CONTENT ADD CONSTRAINT FK_CONTENT_CONTENT_COURSE FOREIGN KEY (GROUP_CONTENT_ID)
REFERENCES CONTENT_COURSE (GROUP_CONTENT_ID)
ON DELETE CASCADE;

ALTER TABLE CONTENT ADD CONSTRAINT FK_CONTENT_FILE FOREIGN KEY (FILE_ID)
REFERENCES APP_FILE (FILE_ID)
ON DELETE SET NULL;

ALTER TABLE CONTENT_COURSE ADD CONSTRAINT FK_CONTENT_COURSE_COURSE FOREIGN KEY (COURSE_ID)
REFERENCES COURSE (COURSE_ID)
ON DELETE CASCADE;

ALTER TABLE COURSE ADD CONSTRAINT FK_COURSE_CENTER FOREIGN KEY (CENTER_ID)
REFERENCES CENTER (CENTER_ID)
ON DELETE CASCADE;

ALTER TABLE COURSE ADD CONSTRAINT FK_COURSE_GROUP FOREIGN KEY (GROUP_ID)
REFERENCES CHAT_GROUP (GROUP_ID)
ON DELETE SET NULL;

ALTER TABLE USER_ACTION ADD CONSTRAINT FK_USER_ACTION_USER FOREIGN KEY (USER_ID)
REFERENCES APP_USER (USER_ID)
ON DELETE CASCADE;

ALTER TABLE USER_CENTER ADD CONSTRAINT FK_USER_CENTER_CENTER FOREIGN KEY (CENTER_ID)
REFERENCES CENTER (CENTER_ID)
ON DELETE CASCADE;

ALTER TABLE USER_CENTER ADD CONSTRAINT FK_USER_CENTER_USER FOREIGN KEY (USER_ID)
REFERENCES APP_USER (USER_ID)
ON DELETE CASCADE;

ALTER TABLE USER_COURSE ADD CONSTRAINT FK_USER_COURSE_COURSE FOREIGN KEY (COURSE_ID)
REFERENCES COURSE (COURSE_ID)
ON DELETE CASCADE;

ALTER TABLE USER_COURSE ADD CONSTRAINT FK_USER_COURSE_USER FOREIGN KEY (USER_ID)
REFERENCES APP_USER (USER_ID)
ON DELETE CASCADE;

ALTER TABLE APP_USER ADD CONSTRAINT CK__USER__ROLE CHECK (ROLE = 'ADMIN' OR ROLE = 'USER');

ALTER TABLE `USER_GROUP` ADD CONSTRAINT `FK_USER_GROUP_GROUP` FOREIGN KEY (`GROUP_ID`)
REFERENCES `CHAT_GROUP` (`GROUP_ID`) ON DELETE CASCADE;

ALTER TABLE `USER_GROUP` ADD CONSTRAINT `FK_USER_GROUP_USER` FOREIGN KEY (`USER_ID`)
REFERENCES `APP_USER` (`USER_ID`) ON DELETE CASCADE;

INSERT INTO APP_USER (USER_ID, EMAIL, PASSWORD, USERNAME, FIRST_NAME, LAST_NAME, SIGN_DATE, IMAGE, ROLE, LAST_SEEN, SALT, PASS_TEST, APPROVED) 
VALUES
(1, 'ff8585ff@gmail.com', '0xCD4136D45338C9E948FC0372C76B961AAC824A928530DD279B7111187B0277B472EBE7B0420F98D59AA887EAFB674AB491AD72226C21488385F5D1764B0D0EF1', 'ADMIN', 'Felix', 'Martinez', '2023-03-27 07:14:46.617', 'default_user_logo.svg', 'ADMIN', '2023-05-25 17:48:12.867', 'Ëbì"+ÄuÌ®-¥åè^ÇÏCc®3b¹lg2Ì\g5¼ÑÆ, BÖJ=', '-Admin123-', 1),
(2, 'felixmb99@hotmail.es', '0x2EE462709F0FF6A2DE5E1D29B8EDD502776BC03E3B1466369656AE1077F5E997E01C840738B653D57A8948B6C6A52FD72A2A4DF2BE6292D4A460B34EDE63D7C8', 'Felix 2', 'Felix 2', 'Martinez Bendicho', '2023-03-27 07:21:16.723', 'image_2.png', 'USER', '2023-03-27 12:56:45.683', 'lQ×/YÃÐowu«8¨Ö@ Dk¼ÌáÎÝB`ïfÑá©Bð', '-Admin123-', 1),
(3, 'mis777pezonesentuboca@gmail.com', '0xA30FE2873D0873C968F78F7E6EA50A8CD628C1F1F24361DD08132FEBB6CC6A57D083608904AD65825C27596490A5331493EE756D2FE348C6C80AEF5AD427F42A', 'ADMIN2', 'Felix', 'Martínez Bendicho', '2023-05-15 20:13:59.273', 'image_0', 'USER', '2023-05-15 22:28:57.783', 'Ð''4N@y·ªp¡B{þ2¾u T[RNiÏw®Ïwã©ÒÄkû¿ÈJ"¢', '-Admin123-', 1);

INSERT INTO CENTER (CENTER_ID, EMAIL, NAME, ADDRESS, IMAGE, TELEPHONE, DIRECTOR, APPROVED) VALUES (1, 'ff8585ff@gmail.com', 'TAJAMAR TECH', 'C. de Pío Felipe, 12, 28038 Madrid', 'center_image_1.jpg', '666666666', 1, 0);
INSERT INTO CENTER (CENTER_ID, EMAIL, NAME, ADDRESS, IMAGE, TELEPHONE, DIRECTOR, APPROVED) VALUES (2, 'example@example.com', 'IES Clara del Rey 2', 'Calle del Padre Claret, 8', 'center_image_2.jpg', '999999999', 1, 1);
INSERT INTO CENTER (CENTER_ID, EMAIL, NAME, ADDRESS, IMAGE, TELEPHONE, DIRECTOR, APPROVED) VALUES (3, 'exampel@example.com', 'Test123123', 'Test123123', 'center_image_3.jpg', '999999999', 1, 1);

INSERT INTO CHAT_GROUP (GROUP_ID, IMAGE, NAME) VALUES (0, 'default_course_image.jpeg', 'Mi primer curso 2');
INSERT INTO CHAT_GROUP (GROUP_ID, IMAGE, NAME) VALUES (1, NULL, 'PRIVATE');

INSERT INTO COURSE (COURSE_ID, DATE_PUBLISHED, DATE_MODIFIED, DESCRIPTION, IMAGE, NAME, CENTER_ID, IS_VISIBLE, GROUP_ID, PASSWORD) VALUES (0, '2023-03-27 07:27:02.433', '2023-03-27 07:27:02.433', '#Normas Este es el primer curso del centro IES Clara del Rey. El curso está enfocado a informática para los alumnos de FP.', 'default_course_image.jpeg', 'Mi primer curso', 2, 1, 0, NULL);

INSERT INTO CONTENT_COURSE (GROUP_CONTENT_ID, NAME, IS_VISIBLE, COURSE_ID) VALUES (0, 'Unidad 2', 0, 0);
INSERT INTO CONTENT_COURSE (GROUP_CONTENT_ID, NAME, IS_VISIBLE, COURSE_ID) VALUES (1, 'Test content group', 0, 0);

INSERT INTO `USER_GROUP` (`ID`, `USER_ID`, `GROUP_ID`, `JOIN_DATE`, `LAST_SEEN`, `IS_ADMIN`) VALUES
(0, 1, 0, '2023-03-27 07:29:53.903', '2023-05-17 18:20:58.487', 1),
(1, 2, 0, '2023-03-27 12:44:16.300', '2023-03-27 12:46:03.033', 0),
(2, 1, 1, '2023-03-27 12:47:37.873', '2023-05-15 23:31:16.860', 0),
(3, 2, 1, '2023-03-27 12:47:37.873', '2023-03-27 12:47:46.623', 0);

INSERT INTO APP_FILE (FILE_ID, USER_ID, MIME_TYPE, NAME) VALUES (1, 1, 'application/pdf', 'content_file_1');
INSERT INTO APP_FILE (FILE_ID, USER_ID, MIME_TYPE, NAME) VALUES (3, 1, 'application/pdf', 'content_file_3');
INSERT INTO APP_FILE (FILE_ID, USER_ID, MIME_TYPE, NAME) VALUES (4, 1, 'image/jpeg', 'content_file_4');
INSERT INTO APP_FILE (FILE_ID, USER_ID, MIME_TYPE, NAME) VALUES (5, 1, 'application/pdf', 'content_file_5');
INSERT INTO APP_FILE (FILE_ID, USER_ID, MIME_TYPE, NAME) VALUES (6, 1, 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'content_file_6');
INSERT INTO APP_FILE (FILE_ID, USER_ID, MIME_TYPE, NAME) VALUES (8, 1, 'application/pdf', 'content_file_8');

INSERT INTO CHAT_MESSAGE (MESSAGE_ID, GROUP_ID, TEXT, USER_ID, DATE_POSTED, FILE_ID, USERNAME) VALUES (1, 0, '', 2, '2023-03-27 12:46:04.630', NULL, 'Felix 2');
INSERT INTO CHAT_MESSAGE (MESSAGE_ID, GROUP_ID, TEXT, USER_ID, DATE_POSTED, FILE_ID, USERNAME) VALUES (2, 0, '', 2, '2023-03-27 12:46:28.403', NULL, 'Felix 2');
INSERT INTO CHAT_MESSAGE (MESSAGE_ID, GROUP_ID, TEXT, USER_ID, DATE_POSTED, FILE_ID, USERNAME) VALUES (3, 1, '', 2, '2023-03-27 12:47:48.140', NULL, 'Felix 2');
INSERT INTO CHAT_MESSAGE (MESSAGE_ID, GROUP_ID, TEXT, USER_ID, DATE_POSTED, FILE_ID, USERNAME) VALUES (4, 0, 'asdf', 1, '2023-05-15 19:24:20.260', NULL, 'ADMIN');
INSERT INTO CHAT_MESSAGE (MESSAGE_ID, GROUP_ID, TEXT, USER_ID, DATE_POSTED, FILE_ID, USERNAME) VALUES (5, 0, 'asdf', 1, '2023-05-15 19:25:37.243', NULL, 'ADMIN');
INSERT INTO CHAT_MESSAGE (MESSAGE_ID, GROUP_ID, TEXT, USER_ID, DATE_POSTED, FILE_ID, USERNAME) VALUES (6, 0, 'asdf', 1, '2023-05-15 23:32:14.587', NULL, 'ADMIN');
INSERT INTO CHAT_MESSAGE (MESSAGE_ID, GROUP_ID, TEXT, USER_ID, DATE_POSTED, FILE_ID, USERNAME) VALUES (7, 0, 'asdf', 1, '2023-05-15 23:32:41.143', NULL, 'ADMIN');
INSERT INTO CHAT_MESSAGE (MESSAGE_ID, GROUP_ID, TEXT, USER_ID, DATE_POSTED, FILE_ID, USERNAME) VALUES (8, 0, 'puta', 1, '2023-05-15 23:32:46.337', NULL, 'ADMIN');
INSERT INTO CHAT_MESSAGE (MESSAGE_ID, GROUP_ID, TEXT, USER_ID, DATE_POSTED, FILE_ID, USERNAME) VALUES (9, 0, 'puta', 1, '2023-05-15 23:33:20.683', NULL, 'ADMIN');
INSERT INTO CHAT_MESSAGE (MESSAGE_ID, GROUP_ID, TEXT, USER_ID, DATE_POSTED, FILE_ID, USERNAME) VALUES (10, 0, 'aria ulna bez un Varco chikitito', 1, '2023-05-15 23:34:34.493', NULL, 'ADMIN');
INSERT INTO CHAT_MESSAGE (MESSAGE_ID, GROUP_ID, TEXT, USER_ID, DATE_POSTED, FILE_ID, USERNAME) VALUES (11, 0, 'Moderated message', 1, '2023-05-15 23:36:01.867', NULL, 'ADMIN');
INSERT INTO CHAT_MESSAGE (MESSAGE_ID, GROUP_ID, TEXT, USER_ID, DATE_POSTED, FILE_ID, USERNAME) VALUES (12, 0, 'Barco', 1, '2023-05-15 23:36:15.327', NULL, 'ADMIN');
INSERT INTO CHAT_MESSAGE (MESSAGE_ID, GROUP_ID, TEXT, USER_ID, DATE_POSTED, FILE_ID, USERNAME) VALUES (13, 0, 'Moderated message', 1, '2023-05-15 23:36:26.827', NULL, 'ADMIN');
INSERT INTO CHAT_MESSAGE (MESSAGE_ID, GROUP_ID, TEXT, USER_ID, DATE_POSTED, FILE_ID, USERNAME) VALUES (14, 0, 'Moderated message', 1, '2023-05-15 23:36:38.970', NULL, 'ADMIN');
INSERT INTO CHAT_MESSAGE (MESSAGE_ID, GROUP_ID, TEXT, USER_ID, DATE_POSTED, FILE_ID, USERNAME) VALUES (15, 0, 'Moderated message', 1, '2023-05-15 23:36:50.753', NULL, 'ADMIN');
INSERT INTO CHAT_MESSAGE (MESSAGE_ID, GROUP_ID, TEXT, USER_ID, DATE_POSTED, FILE_ID, USERNAME) VALUES (16, 0, 'Moderated message', 1, '2023-05-15 23:37:04.210', NULL, 'ADMIN');
INSERT INTO CHAT_MESSAGE (MESSAGE_ID, GROUP_ID, TEXT, USER_ID, DATE_POSTED, FILE_ID, USERNAME) VALUES (17, 0, 'Moderated message', 1, '2023-05-15 23:37:23.630', NULL, 'ADMIN');
INSERT INTO CHAT_MESSAGE (MESSAGE_ID, GROUP_ID, TEXT, USER_ID, DATE_POSTED, FILE_ID, USERNAME) VALUES (18, 0, 'Moderated message', 1, '2023-05-15 23:37:34.500', NULL, 'ADMIN');
INSERT INTO CHAT_MESSAGE (MESSAGE_ID, GROUP_ID, TEXT, USER_ID, DATE_POSTED, FILE_ID, USERNAME) VALUES (19, 0, 'Moderated message', 1, '2023-05-15 23:37:43.367', NULL, 'ADMIN');
INSERT INTO CHAT_MESSAGE (MESSAGE_ID, GROUP_ID, TEXT, USER_ID, DATE_POSTED, FILE_ID, USERNAME) VALUES (20, 0, 'Moderated message', 1, '2023-05-15 23:37:56.193', NULL, 'ADMIN');
INSERT INTO CHAT_MESSAGE (MESSAGE_ID, GROUP_ID, TEXT, USER_ID, DATE_POSTED, FILE_ID, USERNAME) VALUES (21, 0, 'Moderated message', 1, '2023-05-15 23:38:10.180', NULL, 'ADMIN');

INSERT INTO CONTENT (CONTENT_ID, TEXT, GROUP_CONTENT_ID, FILE_ID) VALUES (0, 'test
# hola


- hoa
- test', 0, NULL);

INSERT INTO USER_ACTION (ID, USER_ID, TOKEN, REQUEST_DATE) VALUES (1, 2, '27896785-163a-4a7f-8ec2-ffe680aedc00', '2023-03-27 09:21:16.870');
INSERT INTO USER_ACTION (ID, USER_ID, TOKEN, REQUEST_DATE) VALUES (2, 2, 'b4088b3d-6ee4-4d93-84e4-996997b9f001', '2023-03-27 12:40:37.517');
INSERT INTO USER_CENTER (ID, USER_ID, CENTER_ID, IS_EDITOR) VALUES (1, 1, 1, 1);
INSERT INTO USER_CENTER (ID, USER_ID, CENTER_ID, IS_EDITOR) VALUES (0, 1, 2, 1);
INSERT INTO USER_CENTER (ID, USER_ID, CENTER_ID, IS_EDITOR) VALUES (3, 2, 2, 0);
INSERT INTO USER_CENTER (ID, USER_ID, CENTER_ID, IS_EDITOR) VALUES (4, 3, 2, 0);
INSERT INTO USER_CENTER (ID, USER_ID, CENTER_ID, IS_EDITOR) VALUES (2, 1, 3, 1);
INSERT INTO USER_COURSE (ID, USER_ID, COURSE_ID, IS_EDITOR) VALUES (0, 1, 0, 1);
INSERT INTO USER_COURSE (ID, USER_ID, COURSE_ID, IS_EDITOR) VALUES (1, 2, 0, 0);