CREATE OR ALTER PROCEDURE SP_CREATE_CONTENT
(@TEXT NVARCHAR(MAX), @GROUPCONTENT INT, @FILEID INT = NULL)
AS
	--Generate new ID
	DECLARE @NEWID INT;
	SELECT @NEWID = MAX(CONTENT_ID) + 1 FROM CONTENT;

	IF (@NEWID IS NULL) BEGIN
		SET @NEWID = 0;
	END

	INSERT INTO CONTENT VALUES (@NEWID, @TEXT, @GROUPCONTENT, @FILEID);
GO

CREATE OR ALTER PROCEDURE SP_DELETE_CONTENT
(@CONTENTID INT)
AS
	DELETE FROM CONTENT WHERE CONTENT_ID = @CONTENTID;
GO

CREATE OR ALTER PROCEDURE SP_COURSE_CONTENT
(@COURSE_ID INT)
AS
	-- Course arquitecture: Course -> Contents Course (groups of content) -> Content
	SELECT CT.CONTENT_ID, CT.[TEXT], CT.[FILE_ID] 
	FROM CONTENT CT INNER JOIN CONTENT_COURSE CC
	ON CT.GROUP_CONTENT_ID = CC.GROUP_CONTENT_ID
	WHERE CC.COURSE_ID = @COURSE_ID;
GO

CREATE OR ALTER PROCEDURE SP_GROUP_CONTENT
(@GROUP_CONTENT_ID INT)
AS
	-- Course arquitecture: Course -> Contents Course (groups of content) -> Content
	SELECT C.CONTENT_ID, C.FILE_ID, C.TEXT
	FROM CONTENT C INNER JOIN CONTENT_COURSE GC
	ON C.GROUP_CONTENT_ID = GC.GROUP_CONTENT_ID
	WHERE GC.GROUP_CONTENT_ID = @GROUP_CONTENT_ID;
GO
