CREATE OR ALTER PROCEDURE SP_CREATE_FILE
(@NAME NVARCHAR(MAX), @MIME_TYPE NVARCHAR(100), @USER_ID INT = NULL, @FILE_ID INT OUTPUT)
AS
	DECLARE @FILEID INT;
	SELECT @FILEID = MAX([FILE_ID]) + 1 FROM [FILE];

	IF (@FILEID IS NULL) BEGIN
		SET @FILEID = 0;
	END

	INSERT INTO [FILE] VALUES (@FILEID, @USER_ID, @MIME_TYPE, @NAME);
	
	SET @FILE_ID = @FILEID;
GO

CREATE OR ALTER PROCEDURE SP_DELETE_FILE
(@FILEID INT)
AS
	DELETE FROM [FILE] WHERE [FILE_ID] = @FILEID;
GO