CREATE OR ALTER PROCEDURE SP_CREATE_GROUP
(@NAME NVARCHAR(45), @IMAGE NVARCHAR(MAX) = NULL, @GROUPID INT OUTPUT)
AS
	DECLARE @GROUP_ID INT;
	SELECT @GROUP_ID = (MAX([GROUP].GROUP_ID) + 1) FROM [GROUP];

	IF (@GROUP_ID IS NULL) BEGIN
		SET @GROUP_ID = 0;
	END

	INSERT INTO [GROUP] VALUES (@GROUP_ID, @IMAGE, @NAME);

	SET @GROUPID = @GROUP_ID;
GO

CREATE OR ALTER PROCEDURE SP_UPDATE_GROUP
(@GROUP_ID INT, @NAME NVARCHAR(45), @IMAGE NVARCHAR(MAX) = NULL)
AS
	UPDATE [GROUP] SET NAME = @NAME, IMAGE = @IMAGE;
GO

CREATE OR ALTER PROCEDURE SP_DELETE_GROUP
(@GROUP_ID INT)
AS
	DELETE FROM [GROUP] WHERE GROUP_ID = @GROUP_ID;
GO

CREATE OR ALTER PROCEDURE SP_USER_GROUPS
(@USER_ID INT)
AS
	SELECT G.GROUP_ID, G.IMAGE, G.NAME 
	FROM [GROUP] G INNER JOIN USER_GROUP UG
	ON G.GROUP_ID = UG.GROUP_ID
	WHERE UG.[USER_ID] = @USER_ID;
GO