CREATE OR ALTER PROCEDURE SP_CREATE_USER_COURSE
(@USER_ID INT, @COURSE_ID INT, @IS_EDITOR BIT)
AS
	DECLARE @NEWID INT;
	SELECT @NEWID = MAX([ID]) + 1 FROM [USER_COURSE];

	IF (@NEWID IS NULL) BEGIN
		SET @NEWID = 0;
	END

	INSERT INTO [USER_COURSE] VALUES (@NEWID, @USER_ID, @COURSE_ID, @IS_EDITOR);
GO
